r2dbc:
  url: r2dbc:postgresql://localhost:5432/postgres
  username: admin
  password: admin

liquibase:
  url: jdbc:postgresql://localhost:5432/postgres
  user: admin
  password: admin
  change-log: classpath:/db/db.changelog.yml